"""
src/code_review/pr_creator.py
------------------------------
Creates a GitHub PR with the auto-fixed files.

Flow:
  1. Create a new branch: fix/code-review-{date}
  2. Stage all fixed files
  3. Commit with a summary of violations fixed
  4. Push to origin
  5. Open a PR via `gh pr create`

Requirements:
  - git must be initialised in the project
  - `gh` CLI must be installed and authenticated (gh auth login)

Usage:
    from src.code_review.pr_creator import PRCreator
    creator = PRCreator()
    pr_url  = creator.create_pr(fixed_files, violations_summary)
"""

import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict

from src.code_review.scanner import Violation


class PRCreator:
    def __init__(self, repo_root: str = "."):
        self.repo_root = Path(repo_root).resolve()

    # ── Git helpers ───────────────────────────────────────────────────────────

    def _run(self, cmd: List[str], check: bool = True) -> subprocess.CompletedProcess:
        """Run a shell command in the repo root."""
        return subprocess.run(
            cmd,
            cwd=str(self.repo_root),
            capture_output=True,
            text=True,
            check=check,
        )

    def _current_branch(self) -> str:
        result = self._run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
        return result.stdout.strip()

    def _branch_exists(self, branch: str) -> bool:
        result = self._run(
            ["git", "branch", "--list", branch], check=False
        )
        return bool(result.stdout.strip())

    # ── PR body builder ───────────────────────────────────────────────────────

    @staticmethod
    def _build_pr_body(
        results: Dict[str, List[Violation]],
        fixed_files: List[str],
    ) -> str:
        total = sum(len(v) for v in results.values())

        severity_counts = {"Critical": 0, "Major": 0, "Minor": 0, "Info": 0}
        for violations in results.values():
            for v in violations:
                sev = v.severity.capitalize()
                if sev in severity_counts:
                    severity_counts[sev] += 1

        lines = [
            "## Summary",
            f"- **{total} violation(s)** fixed across **{len(fixed_files)} file(s)**",
            f"- Critical: {severity_counts['Critical']} | "
            f"Major: {severity_counts['Major']} | "
            f"Minor: {severity_counts['Minor']} | "
            f"Info: {severity_counts['Info']}",
            "",
            "## Files Fixed",
        ]

        for file_path in fixed_files:
            rel = Path(file_path).name
            count = len(results.get(file_path, []))
            lines.append(f"- `{rel}` — {count} fix(es)")

        lines += [
            "",
            "## Violations Fixed",
            "",
            "| File | Line | Rule | Severity | Description |",
            "|------|------|------|----------|-------------|",
        ]

        for file_path, violations in results.items():
            rel = Path(file_path).name
            for v in violations:
                lines.append(
                    f"| `{rel}` | {v.line} | {v.rule_id} | {v.severity} | {v.description} |"
                )

        lines += [
            "",
            "## How rules were detected",
            "This PR was generated by the **RAG Code Review** tool.",
            "Rules are stored in a local ChromaDB vector store (`code_review_rules` collection).",
            "The scanner retrieved relevant rules per file and used a local Ollama LLM to identify and fix violations.",
            "",
            "---",
            "🤖 Generated with RAG Code Review (local, free — Ollama + ChromaDB)",
        ]

        return "\n".join(lines)

    # ── Main PR creation ──────────────────────────────────────────────────────

    def create_pr(
        self,
        fixed_files: List[str],
        results: Dict[str, List[Violation]],
        base_branch: str = "main",
    ) -> str:
        """
        Commit fixed files to a new branch and open a GitHub PR.

        Args:
            fixed_files:  List of file paths that were fixed (written to disk).
            results:      Original scan results for PR body generation.
            base_branch:  Branch to merge into (default: main).

        Returns:
            URL of the created PR.
        """
        if not fixed_files:
            print("⚠️  No fixed files to commit.")
            return ""

        date_str    = datetime.now().strftime("%Y%m%d-%H%M")
        branch_name = f"fix/code-review-{date_str}"

        print(f"\n🌿 Creating branch: {branch_name}")

        # 1. Create and checkout new branch
        if self._branch_exists(branch_name):
            self._run(["git", "checkout", branch_name])
        else:
            self._run(["git", "checkout", "-b", branch_name])

        # 2. Stage only the fixed files
        print(f"📦 Staging {len(fixed_files)} file(s)...")
        for f in fixed_files:
            rel = str(Path(f).relative_to(self.repo_root))
            self._run(["git", "add", rel])

        # 3. Commit
        total      = sum(len(v) for v in results.values())
        commit_msg = (
            f"fix: auto code review — {total} violation(s) in {len(fixed_files)} file(s)\n\n"
            f"Fixed by RAG Code Review tool (Ollama + ChromaDB)\n\n"
            f"Co-Authored-By: RAG Code Reviewer <noreply@local>"
        )
        self._run(["git", "commit", "-m", commit_msg])
        print(f"✅ Committed fixes")

        # 4. Push
        print(f"🚀 Pushing branch to origin...")
        self._run(["git", "push", "-u", "origin", branch_name])

        # 5. Create PR via gh CLI
        pr_title = f"fix: RAG Code Review — {total} violation(s) auto-fixed"
        pr_body  = self._build_pr_body(results, fixed_files)

        print(f"🔀 Creating PR...")
        result = self._run([
            "gh", "pr", "create",
            "--title",  pr_title,
            "--body",   pr_body,
            "--base",   base_branch,
            "--head",   branch_name,
        ])

        pr_url = result.stdout.strip()
        print(f"\n✅ PR created: {pr_url}")
        return pr_url
